Add new mandatory algorithms parameter for JWT to fix error
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().